import {geometry,validatePolygon} from './geometry.js';
export const uid=()=>globalThis.crypto.randomUUID();
export const clone=x=>JSON.parse(JSON.stringify(x));
export function shape(type,x,y,w=160,h=24){const result={id:uid(),type,x,y,w,h,angle:0,color:'#7397ab',vertices:[],motion:{type:'fixed',anchor:{x:0,y:0},speed:60,path:[],playback:'pingpong'}};if(type==='teleporter'){result.color='#238b9c';result.destination={x:x+150,y};}return result;}
export function newMap(){return {version:1,id:uid(),name:'Untitled playground',width:900,height:1400,gravity:0.6,start:{x:300,y:60,w:300,h:100},finish:{x:40,y:1290,w:820,h:30},objects:[]};}
export function demo(){const m=newMap();m.name='The first descent';m.objects=[shape('wall',20,700,20,1400),shape('wall',880,700,20,1400),shape('wall',240,300,350,22),shape('wall',660,300,350,22),shape('rectangle',450,600,260,26),shape('rectangle',450,940,210,26)];m.objects[2].angle=18;m.objects[3].angle=-18;m.objects[4].color='#e7b668';m.objects[4].motion.type='rotate';m.objects[5].color='#c798df';m.objects[5].motion={...m.objects[5].motion,type:'path',speed:100,path:[{x:230,y:940},{x:670,y:940}]};return m;}
export function validate(m,{prefab=false}={}){const fail=s=>{throw Error(s)};const num=(v,min,max,label)=>{if(!Number.isFinite(v)||v<min||v>max)fail(`${label} must be between ${min} and ${max}.`)};if(!m||m.version!==1)fail('Unsupported map version; expected version 1.');if(typeof m.id!=='string'||typeof m.name!=='string'||m.name.length>120)fail('Map needs an ID and a name (up to 120 characters).');num(m.width,200,10000,'Map width');num(m.height,200,20000,'Map height');num(m.gravity,-5,5,'Gravity');const point=p=>{if(!p)fail('Missing point.');num(p.x,-30000,30000,'X');num(p.y,-30000,30000,'Y')};for(const k of ['start','finish']){point(m[k]);num(m[k].w,10,10000,k+' width');num(m[k].h,10,20000,k+' height');}if(!Array.isArray(m.objects)||m.objects.length>1000)fail('Map must contain at most 1000 objects.');const ids=new Set();for(const o of m.objects){if(typeof o.id!=='string'||ids.has(o.id))fail('Object IDs must be unique.');ids.add(o.id);if(!['wall','rectangle','circle','oval','marble','polygon','teleporter'].includes(o.type))fail('Unknown shape type.');point(o);if(o.type==='teleporter'){point(o.destination);if(o.motion?.type!=='fixed'||o.cuts?.length)fail('Teleport blocks must be fixed and uncut.');if(!prefab){num(o.destination.x,24,m.width-24,'Destination X');num(o.destination.y,24,m.height-24,'Destination Y');}}if(o.type==='marble'&&(o.w!==16||o.h!==16||o.motion?.type!=='fixed'||o.cuts?.length))fail('Scale marbles must be fixed, uncut, and 16 pixels wide.');num(o.w,4,20000,'Width');num(o.h,4,20000,'Height');num(o.angle,-36000,36000,'Angle');if(!/^#[0-9a-f]{6}$/i.test(o.color))fail('Shape color must be a hex color.');if(o.type==='polygon'){if(!Array.isArray(o.vertices)||o.vertices.length<3||o.vertices.length>100)fail('Polygons need 3–100 vertices.');o.vertices.forEach(point);validatePolygon(o.vertices);}if(!o.motion||!['fixed','rotate','path','pathRotate','teleport'].includes(o.motion.type))fail('Unknown motion behavior.');if(o.motion.type==='pathRotate')num(o.motion.rotationSpeed,-720,720,'Rotation speed');
if(o.cuts!==undefined){if(!Array.isArray(o.cuts)||o.cuts.length>30)fail('Use at most 30 cuts per shape.');for(const c of o.cuts){if(!c||!['circle','rectangle','oval'].includes(c.type))fail('Unknown cut type.');point(c);num(c.w,4,20000,'Cut width');num(c.h,4,20000,'Cut height');num(c.angle,-36000,36000,'Cut angle');}if(!geometry(o).length)fail('This cut removes the entire shape. Delete the shape instead.');}
if(o.motion.type==='teleport')num(o.motion.interval,.1,3600,'Teleport interval');if(o.oneWay!==undefined&&!['none','up','down','left','right'].includes(o.oneWay))fail('Unknown gate direction.');if(o.material!==undefined){if(!o.material)fail('Missing material.');num(o.material.bounce,0,1,'Bounciness');num(o.material.friction,0,1,'Friction');}
point(o.motion.anchor);num(o.motion.speed,-720,720,'Motion speed');if(!Array.isArray(o.motion.path)||o.motion.path.length>100)fail('Path must contain at most 100 points.');o.motion.path.forEach(point);if(!['loop','pingpong'].includes(o.motion.playback))fail('Unknown path playback.');if(['path','pathRotate'].includes(o.motion.type)&&o.motion.path.length<2)fail('Moving shapes need at least two path points.');}return m;}
export function pose(o,t){let x=o.x,y=o.y,angle=o.angle*Math.PI/180;const m=o.motion;if((m.type==='path'||m.type==='pathRotate')&&m.path.length>1){const p=[...m.path];const lengths=p.slice(1).map((v,i)=>Math.hypot(v.x-p[i].x,v.y-p[i].y));const total=lengths.reduce((a,b)=>a+b,0);if(total){let d=((t*m.speed)%(total*(m.playback==='loop'?1:2))+total*(m.playback==='loop'?1:2))%(total*(m.playback==='loop'?1:2));if(d>total)d=2*total-d;for(let i=0;i<lengths.length;i++){if(d<=lengths[i]&&lengths[i]>0){const f=d/lengths[i];x=p[i].x+(p[i+1].x-p[i].x)*f;y=p[i].y+(p[i+1].y-p[i].y)*f;break;}d-=lengths[i];}}}if(m.type==='teleport'&&m.path.length){const point=m.path[Math.floor(t/m.interval)%m.path.length];x=point.x;y=point.y;}if(m.type==='rotate'||m.type==='pathRotate'){const a=m.anchor,base=angle;angle+=t*(m.type==='pathRotate'?m.rotationSpeed:m.speed)*Math.PI/180;x+=Math.cos(base)*a.x-Math.sin(base)*a.y-Math.cos(angle)*a.x+Math.sin(angle)*a.y;y+=Math.sin(base)*a.x+Math.cos(base)*a.y-Math.sin(angle)*a.x-Math.cos(angle)*a.y;}return {x,y,angle};}


// Walls sit outside the playable area, with their inner faces on the map edges.
export function boundaryWalls(map){const t=20,w=map.width,h=map.height;return [
{x:w/2,y:-t/2,w:w+2*t,h:t},
{x:w/2,y:h+t/2,w:w+2*t,h:t},
{x:-t/2,y:h/2,w:t,h},
{x:w+t/2,y:h/2,w:t,h}
];}
