// Resize in the shape's rotated coordinate system while keeping the opposite edge fixed.
const rotate=(p,a)=>({x:p.x*Math.cos(a)-p.y*Math.sin(a),y:p.x*Math.sin(a)+p.y*Math.cos(a)});
const center=(o,region)=>({x:o.x+(region?o.w/2:0),y:o.y+(region?o.h/2:0)});
export function resizeHandles(o,region=false){const c=center(o,region),a=(o.angle||0)*Math.PI/180;return [[-1,-1],[0,-1],[1,-1],[-1,0],[1,0],[-1,1],[0,1],[1,1]].map(([sx,sy])=>{const p=rotate({x:sx*o.w/2,y:sy*o.h/2},a);return{sx,sy,x:c.x+p.x,y:c.y+p.y};});}
export function resizeHit(o,p,scale,region=false){const tolerance=7/scale,handles=resizeHandles(o,region),nearest=handles.map(h=>({...h,d:Math.hypot(h.x-p.x,h.y-p.y)})).sort((a,b)=>a.d-b.d)[0];if(nearest.d<=tolerance)return nearest;const c=center(o,region),v=rotate({x:p.x-c.x,y:p.y-c.y},-(o.angle||0)*Math.PI/180);if(Math.abs(v.x)<=o.w/2&&Math.abs(Math.abs(v.y)-o.h/2)<=tolerance)return{sx:0,sy:Math.sign(v.y)||1};if(Math.abs(v.y)<=o.h/2&&Math.abs(Math.abs(v.x)-o.w/2)<=tolerance)return{sx:Math.sign(v.x)||1,sy:0};return null;}
export function resizeCursor(h,angle=0){const direction=(Math.atan2(h.sy,h.sx)*180/Math.PI+angle+360)%180;return ['ew-resize','nwse-resize','ns-resize','nesw-resize'][Math.round(direction/45)%4];}
export function resizeShape(original,handle,start,end,region=false){const o=structuredClone(original),a=(o.angle||0)*Math.PI/180,d=rotate({x:end.x-start.x,y:end.y-start.y},-a),min=region?10:4;let w=handle.sx?Math.max(min,o.w+handle.sx*d.x):o.w,h=handle.sy?Math.max(min,o.h+handle.sy*d.y):o.h;if(o.type==='circle'){const size=!handle.sx?h:!handle.sy?w:Math.abs(w-o.w)>=Math.abs(h-o.h)?w:h;w=h=size;}w=Math.min(20000,w);h=Math.min(20000,h);const shift={x:handle.sx*(w-o.w)/2,y:handle.sy*(h-o.h)/2},delta=rotate(shift,a),c=center(o,region);o.x=c.x+delta.x-(region?w/2:0);o.y=c.y+delta.y-(region?h/2:0);if(o.type==='polygon')o.vertices=o.vertices.map(p=>({x:p.x*w/o.w,y:p.y*h/o.h}));
// Existing cuts and pins stay at their map positions as the outline stretches.
if(o.cuts)o.cuts=o.cuts.map(c=>({...c,x:c.x-shift.x,y:c.y-shift.y}));if(o.motion){o.motion.anchor.x-=shift.x;o.motion.anchor.y-=shift.y;o.motion.path=o.motion.path.map(p=>({x:p.x+delta.x,y:p.y+delta.y}));}o.w=w;o.h=h;return o;}
